//			MADE BY ROBOKITS INDIA.
//			VISIT US AT WWW.ROBOKITS.ORG
//			PROGRAM FOR INTERRUPT
//			WRITTEN FOR PRODUCT ID 19

/*-------------------------------------------------------------------          
 Description:
 This example shows how to use external interrupts so that cpu is
 free for processing other things. Here cpu is used for blinking led2.

 Note:
 External interrupt is generated by pressing sw1 connected to INT0.
 
 Led2 is blinking with normal delay routine.

 Led3 blinks on external interrupt low edge.
  
 Since _delay_ms() function will be affected by the interrupt generation 
 and gives more delay. So, after sometime the led timing will be mismached.
 
 Even the timer delay is not perfectly mached to 1s. Use smaller presclar
 for better operation.
 
  _delay_ms() function parameter passed should not exeed
 262.14ms / F_CPU in mhz.
 
 so for 16MHz the maximum paramer should be 16ms.
 
 For 1MHz it can be upto 262ms (250 is used for this example).
  
 Must be changed to get accurate delay at higher MHz.
 
 The timing will differ if the operating frequency is changed.
---------------------------------------------------------------------*/

/*----------------------------------------------------------------
-----------------HEADER FILES-------------------------------------
-----------------------------------------------------------------*/
#include <avr/io.h>
#include <avr/interrupt.h>
#include <util/delay.h>
#include <compat/deprecated.h>		//HEADER FILE FOR FUNCTIONS LIKE SBI AND CBI

/*----------------------------------------------------------------
-----------------GLOBAL VARIABLES-------------------------------------
-----------------------------------------------------------------*/

static volatile uint8_t led;     // use volatile when variable is accessed from interrupts
int volatile flag=33;
int volatile count=0;
int volatile no,no1,no2,no3=0;
/*----------------------------------------------------------------
-----------------FUNCTION-----------------------------------------
-----------------------------------------------------------------*/


SIGNAL(SIG_INTERRUPT0)     
/* signal handler for external interrupt int0 */
{

	count++;
	
	if(count==4)
	{
		count=0;
	}
	 _delay_ms(500);
}



SIGNAL(SIG_INTERRUPT1)     
/* signal handler for external interrupt int0 */
{
	int d=250;
	
	while(flag==11)
	{
		if(no==1 && no==3)
		{
			if(no==3)
			{
				no=1;
			}
			sbi(PORTD,6);
			_delay_ms(100);
			cbi(PORTD,6);
			_delay_ms(100);
		}
		if(no==2)
		{
			sbi(PORTD,6);
			_delay_ms(200);
			cbi(PORTD,6);
			_delay_ms(200);
		}
	}
	while(flag==12)
	{
		if(no1==1 && no1==3)
		{
			if(no1==3)
			{
				no1=1;
			}
			sbi(PORTD,6);
			_delay_ms(100);
			cbi(PORTD,6);
			_delay_ms(100);
		}
		if(no1==2)
		{
			sbi(PORTD,6);
			_delay_ms(200);
			cbi(PORTD,6);
			_delay_ms(200);
		}
	}
	while(flag==13)
	{
		if(no2==1 && no2==3)
		{
			if(no2==3)
			{
				no2=1;
			}
			sbi(PORTD,6);
			_delay_ms(100);
			cbi(PORTD,6);
			_delay_ms(100);
		}
		if(no2==2)
		{
			sbi(PORTD,6);
			_delay_ms(200);
			cbi(PORTD,6);
			_delay_ms(200);
		}
	}
	while(flag==10)
	{
		if(no3==1 && no3==3)
		{
			if(no3==3)
			{
				no3=1;
			}
			sbi(PORTD,6);
			_delay_ms(100);
			cbi(PORTD,6);
			_delay_ms(100);
		}
		if(no3==2)
		{
			sbi(PORTD,6);
			_delay_ms(200);
			cbi(PORTD,6);
			_delay_ms(200);
		}
	}
if(flag==33)
{
		for(d;d<3000 ;d=d+250)
		{
			sbi(PORTD,6);
			sbi(PORTD,7);
			_delay_ms(250);
			cbi(PORTD,6);
			cbi(PORTD,7);
			_delay_ms(250);
			if(bit_is_clear(PIND,3))
			{
			}
			else
			{break;}
		}

	}

}



	



/*-----------------MAIN PROGRAM-------------------------------------
----------------------------------------------------------------
-----------------------------------------------------------------*/

int main(void)
{    
	DDRB=0x01;						//SET DATA DIRECTION REGISTER
									//SET 1 for OUTPUT PORT
									//SET 0 FOR INPUT PORT
									//ONLY PORTB.0 IS OUTPUT
									//CONFIGURE AS PER REQUIREMENT
									//DEFAULT ALL OTHERS ARE INPUT
									//CHANGE ACCORDING TO USE
	
	DDRD=0xC0;						//SET DATA DIRECTION REGISTER
									//SET 1 for OUTPUT PORT
									//SET 0 FOR INPUT PORT
									//ONLY PORTD.7 AND PORTD.6 ARE OUTPUT
									//CONFIGURE AS PER REQUIREMENT
									//DEFAULT ALL OTHERS ARE INPUT
									//CHANGE ACCORDING TO USE
	
	sbi(PORTB,0);					//LED1 ON (INDICATION FOR READY TO USE)
	
	sbi(PORTD,2);					//ENABLE PULL UP FOR SW1
	sbi(PORTD,3);					//ENABLE PULL UP FOR SW2
    
    GIMSK = _BV(INT1);
    MCUCR = _BV(ISC11);
  // MCUCR=0x00;
	
    
	sei();                       	// enable interrupts 
    
	
    for (;;) 					 	//BLINK LED2
	{	
		sbi(PORTD,6);
		sbi(PORTD,7);
		_delay_ms(250);
		cbi(PORTD,6);
		cbi(PORTD,7);
		_delay_ms(250);
		if(bit_is_clear(PIND,3))
		{
			cbi(PORTD,6);
			cbi(PORTD,7);
			while(bit_is_clear(PIND,3))
			{
				GIMSK = _BV(INT0);
				MCUCR = 0x02;
				

				if(count==1)
				{
					flag=11;
					sbi(PORTD,6);
					cbi(PORTD,7);
					
				}
				
				else if(count==2)
				{
					flag=12;
					sbi(PORTD,7);
					cbi(PORTD,6);
					
				}
				else if(count==3)
				{
					flag=13;
					sbi(PORTD,6);
					sbi(PORTD,7);
					
				}
				
				  else
				{
					flag=10;
					cbi(PORTD,6);
					cbi(PORTD,7);
					
				}

			
					
			}

		}
		if(flag==11 || flag==12 || flag==13 || flag==10)
		{ 
			//fl11();
			GIMSK=_BV(INT1);
			MCUCR=_BV(ISC11);
			if(flag==11)
			{
				no++;
				_delay_ms(2500);
				_delay_ms(2500);

			}
			if(flag==12)
			{
				no1++;
				_delay_ms(2500);
				_delay_ms(2500);
			}
			if(flag==13)
			{
				no2++;
				_delay_ms(2500);
				_delay_ms(2500);
			}
			if(flag==10)
			{
				no3++;
				_delay_ms(2500);
				_delay_ms(2500);
			}
		}
	
		GIMSK = _BV(INT1);
		MCUCR = _BV(ISC11);
				
	}  

	for(;;)
	{
	}// loop forever   
}

