######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 22 11:17:32 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += usbwidgets.h usbstuff.h mainwidget.h
SOURCES += qusbmot.cpp usbstuff.cpp
LIBS += `libusb-config --libs`

TRANSLATIONS = qusbmot_de.ts