(function(){
var g=false,h=null,m=true,aa=(new Date).getTime();var ba={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_region:"region",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",
google_color_url:"color_url",google_contents:"contents",google_country:"gl",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_gl:"gl",google_hints:"hints",
google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_referrer_url:"ref",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_targeting:"targeting",google_ui_features:"ui",google_ui_version:"uiv",google_tag_js_version:"gut",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},ca={google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_override:"google_ad_override",google_ad_slot:"slotname",
google_analytics_uacct:"ga_wpids",google_correlator:"correlator",google_cpa_choice:"cpa_choice",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_page_location:"loc",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",
google_rt:"rt",google_skip:"skip"},da={google_only_pyv_ads:"pyv"};function ea(a){return ba[a]||ca[a]||da[a]||h};document.URL&&(document.URL.indexOf("?google_debug")>0||document.URL.indexOf("&google_debug")>0);function n(){this.I=this.yb();this.Ta=g;if(!this.I)this.Ta=this.bb()}n.prototype.ia="__gads=";n.prototype.S="GoogleAdServingTest=";n.prototype.ib=function(){return this.I};n.prototype.setCookieInfo=function(a){this.B=a._cookies_[0];if(this.B!=h){this.I=this.B._value_;this.Hb()}};n.prototype.eb=function(a){var b=(new Date).valueOf(),c=new Date;c.setTime(b+a);return c};
n.prototype.db=function(a){if(!(this.I!=h||!this.Ta)){var b="script",c=document.domain,d="http://partner.googleadservices.com/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo&client="+fa(a)+"&domain="+fa(c);document.write("<"+b+' src="'+d+'"></'+b+">")}};n.prototype.bb=function(){document.cookie=this.S+"Good";var a=this.Fa(this.S),b=a=="Good";if(b){var c=this.eb(-1);document.cookie=this.S+"; expires="+c.toGMTString()}return b};n.prototype.yb=function(){var a=this.Fa(this.ia);return a};
n.prototype.Fa=function(a){var b=document.cookie,c=b.indexOf(a),d=h;if(c!=-1){var e=c+a.length,f=b.indexOf(";",e);if(f==-1)f=b.length;d=b.substring(e,f)}return d};n.prototype.Hb=function(){if(!(this.B==h))if(!(this.I==h)){var a=new Date;a.setTime(1000*this.B._expires_);var b=this.B._domain_,c=this.ia+this.I+"; expires="+a.toGMTString()+"; path="+this.B._path_+"; domain=."+b;document.cookie=c}};function ga(a,b){var c;return a?(c=parseFloat(a))?c:b:b}
function ha(a,b){if(a=="true")return m;if(a=="false")return g;return b}
function ia(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){var b=3,c=1;for(;c;)try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(b+1));b++}catch(d){c=h}return b.toString()}else if(ja()){var c=h;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){var b=0;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");
b=6;c.AllowScriptAccess="always"}catch(d){if(b==6)return b.toString()}try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(d){}}if(c!=h){var b=c.GetVariable("$version").split(" ")[1];return b.replace(/,/g,".")}}return"0"};var ka=ka||{},r=this,ma=function(a,b,c){var d=a.split("."),e=c||r,f;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(;d.length&&(f=d.shift());)if(!d.length&&la(b))e[f]=b;else if(e[f])e=e[f];else{e[f]={};e=e[f]}},na=function(a,b){var c=a.split("."),d=b||r,e;for(;e=c.shift();)if(d[e])d=d[e];else return h;return d},pa=function(){},s=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)=="[object Array]")return"array";
if(typeof a.call!="undefined")return"function"}else return"null";else if(b=="function"&&typeof a.call=="undefined")return"object";return b},la=function(a){return typeof a!="undefined"};
var qa=function(a){return s(a)=="function"},ra=function(a){var b=s(a);return b=="object"||b=="array"||b=="function"},ua=function(a){if(a.hasOwnProperty&&a.hasOwnProperty(sa)){var b=a[sa];if(b)return b}a[sa]||(a[sa]=++ta);return a[sa]},sa="closure_hashCode_",ta=0,va=function(a){var b=s(a);if(b=="object"||b=="array"){if(a.clone)return a.clone.call(a);var c=b=="array"?[]:{};for(var d in a)c[d]=va(a[d]);return c}return a},t=function(a,b){var c=a.Ib;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,
2);c&&d.unshift.apply(d,c);c=d}b=a.Kb||b;a=a.Jb||a;var e,f=b||r;e=c?function(){var j=Array.prototype.slice.call(arguments);j.unshift.apply(j,c);return a.apply(f,j)}:function(){return a.apply(f,arguments)};e.Ib=c;e.Kb=b;e.Jb=a;return e},wa=Date.now||function(){return(new Date).getTime()},xa=function(a,b,c){ma(a,b,c)},u=function(a,b){function c(){}c.prototype=b.prototype;a.o=b.prototype;a.prototype=new c;a.prototype.constructor=a};var ya=function(a,b,c){if(a.indexOf)return a.indexOf(b,c);if(Array.indexOf)return Array.indexOf(a,b,c);var d=c==h?0:c<0?Math.max(0,a.length+c):c,e=d;for(;e<a.length;e++)if(e in a&&a[e]===b)return e;return-1},za=function(a,b){var c=ya(a,b),d;if(d=c!=-1)Array.prototype.splice.call(a,c,1).length==1;return d};var Aa=function(a,b){this.x=la(a)?a:0;this.y=la(b)?b:0};Aa.prototype.clone=function(){return new Aa(this.x,this.y)};Aa.prototype.toString=function(){return"("+this.x+", "+this.y+")"};var v=function(a,b){this.width=a;this.height=b};v.prototype.clone=function(){return new v(this.width,this.height)};v.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};v.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};v.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
v.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};v.prototype.scale=function(a){this.width*=a;this.height*=a;return this};var Ba=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Ca=function(a,b){var c=b.length,d=0;for(;d<c;d++){var e=c==1?b:b.charAt(d);if(a.charAt(0)==e&&a.charAt(a.length-1)==e)return a.substring(1,a.length-1)}return a};
var Ea=function(a,b){var c=0,d=Ba(String(a)).split("."),e=Ba(String(b)).split("."),f=Math.max(d.length,e.length),j=0;for(;c==0&&j<f;j++){var i=d[j]||"",l=e[j]||"",k=new RegExp("(\\d*)(\\D*)","g"),o=new RegExp("(\\d*)(\\D*)","g");do{var p=k.exec(i)||["","",""],q=o.exec(l)||["","",""];if(p[0].length==0&&q[0].length==0)break;var K=p[1].length==0?0:parseInt(p[1],10),N=q[1].length==0?0:parseInt(q[1],10);c=Da(K,N)||Da(p[2].length==0,q[2].length==0)||Da(p[2],q[2])}while(c==0)}return c},Da=function(a,b){if(a<
b)return-1;else if(a>b)return 1;return 0};var Fa,Ga,Ha,Ia,Ja,Ka,La,Ma,Na,Oa=function(){return r.navigator?r.navigator.userAgent:h};var Pa=function(){Ka=Ja=Ia=Ha=Ga=Fa=g;var a;if(a=Oa()){var b=r.navigator;Fa=a.indexOf("Opera")==0;Ga=!Fa&&a.indexOf("MSIE")!=-1;Ia=(Ha=!Fa&&a.indexOf("WebKit")!=-1)&&a.indexOf("Mobile")!=-1;Ka=(Ja=!Fa&&!Ha&&b.product=="Gecko")&&b.vendor=="Camino"}};Pa();
var Qa=Fa,w=Ga,Ra=Ja,Sa=Ka,x=Ha,Ta=Ia,Ua=function(){var a=r.navigator;return a&&a.platform||""},Va=Ua(),Wa=function(){La=Va.indexOf("Mac")!=-1;Ma=Va.indexOf("Win")!=-1;Na=Va.indexOf("Linux")!=-1};Wa();var Xa=La,Ya=Ma,Za=Na,$a=function(){var a="",b;if(Qa&&r.opera){var c=r.opera.version;a=typeof c=="function"?c():c}else{if(Ra)b=/rv\:([^\);]+)(\)|;)/;else if(w)b=/MSIE\s+([^\);]+)(\)|;)/;else if(x)b=/WebKit\/(\S+)/;if(b){var d=b.exec(Oa());a=d?d[1]:""}}return a},ab=$a();
var y=function(a){return Ea(ab,a)>=0};var bb;var hb=function(a){return a?new z(cb(a)):bb||(bb=new z)};var ib=function(a){return typeof a=="string"?document.getElementById(a):a},jb=ib,kb=function(a){var b=a||r||window,c=b.document;if(x&&!y("500")&&!Ta){if(typeof b.innerHeight=="undefined")b=window;var d=b.innerHeight,e=b.document.documentElement.scrollHeight;if(b==b.top)if(e<d)d-=15;return new v(b.innerWidth,d)}var f=hb(c),j=f.Z()&&(!Qa||Qa&&y("9.50"))?c.documentElement:c.body;return new v(j.clientWidth,j.clientHeight)};
var lb=function(a,b){a.appendChild(b)},mb=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):h},nb=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)},ob=x&&Ea(ab,"521")<=0,pb=function(a,b){if(typeof a.contains!="undefined"&&!ob&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a},cb=function(a){return a.nodeType==9?a:a.ownerDocument||a.document},z=
function(a){this.C=a||r.document||document};z.prototype.wa=function(){return this.C};z.prototype.ya=function(a){return typeof a=="string"?this.C.getElementById(a):a};z.prototype.createElement=function(a){return this.C.createElement(a)};z.prototype.createTextNode=function(a){return this.C.createTextNode(a)};
z.prototype.Z=function(){var a=this.C;if(a.compatMode)return a.compatMode=="CSS1Compat";if(x){var b=a.createElement("div");b.style.cssText="position:absolute;width:0;height:0;width:1";var c=b.style.width=="1px"?"BackCompat":"CSS1Compat";return(a.compatMode=c)=="CSS1Compat"}return g};z.prototype.gb=function(){var a=this.C;return!x&&this.Z()?a.documentElement:a.body};z.prototype.xa=function(){var a=this.gb();return new Aa(a.scrollLeft,a.scrollTop)};z.prototype.appendChild=lb;
z.prototype.removeNode=mb;z.prototype.replaceNode=nb;z.prototype.contains=pb;var qb,rb=function(a,b){var c=cb(a);if(c.defaultView&&c.defaultView.getComputedStyle){var d=c.defaultView.getComputedStyle(a,"");if(d)return d[b]}return h};var sb=function(a,b){return rb(a,b)||(a.currentStyle?a.currentStyle[b]:h)||a.style[b]};
var tb=function(a){var b;b=a?a.nodeType==9?a:cb(a):document;if(w&&!hb(b).Z())return b.body;return b.documentElement},ub=function(a){var b=a.getBoundingClientRect();if(w){var c=a.ownerDocument;b.left-=c.documentElement.clientLeft+c.body.clientLeft;b.top-=c.documentElement.clientTop+c.body.clientTop}return b},vb=function(a){if(w)return a.offsetParent;var b=cb(a),c=sb(a,"position"),d=c=="fixed"||c=="absolute",e=a.parentNode;for(;e&&e!=b;e=e.parentNode){c=sb(e,"position");d=d&&c=="static"&&e!=b.documentElement&&
e!=b.body;if(!d&&(e.scrollWidth>e.clientWidth||e.scrollHeight>e.clientHeight||c=="fixed"||c=="absolute"))return e}return h},wb=function(a){var b,c=cb(a),d=sb(a,"position"),e=Ra&&c.getBoxObjectFor&&!a.getBoundingClientRect&&d=="absolute"&&(b=c.getBoxObjectFor(a))&&(b.screenX<0||b.screenY<0);if(typeof qb=="undefined")qb=Sa&&!y("1.8.0.11");var f=new Aa(0,0),j=tb(c);if(a==j)return f;if(a.getBoundingClientRect){b=ub(a);var i=hb(c).xa();f.x=b.left+i.x;f.y=b.top+i.y}else if(c.getBoxObjectFor&&!e&&!qb){b=
c.getBoxObjectFor(a);var l=c.getBoxObjectFor(j);f.x=b.screenX-l.screenX;f.y=b.screenY-l.screenY}else{var k=a;do{f.x+=k.offsetLeft;f.y+=k.offsetTop;if(k!=a){f.x+=k.clientLeft||0;f.y+=k.clientTop||0}if(x&&sb(k,"position")=="fixed"){f.x+=c.body.scrollLeft;f.y+=c.body.scrollTop;break}k=k.offsetParent}while(k&&k!=a);if(Qa||x&&d=="absolute")f.y-=c.body.offsetTop;k=a;for(;(k=vb(k))&&k!=c.body;){f.x-=k.scrollLeft;if(!Qa||k.tagName!="TR")f.y-=k.scrollTop}}return f},xb=function(a){var b=new Aa;if(a.nodeType==
1)if(a.getBoundingClientRect){var c=ub(a);b.x=c.left;b.y=c.top}else{var d=hb(a).xa(),e=wb(a);b.x=e.x-d.x;b.y=e.y-d.y}else{b.x=a.clientX;b.y=a.clientY}return b},yb=function(a){var b=cb(a),c="";if(b.createTextRange){var d=b.body.createTextRange();d.moveToElementText(a);c=d.queryCommandValue("FontName")}if(!c){c=sb(a,"fontFamily");if(Qa&&Za)c=c.replace(/ \[[^\]]*\]/,"")}var e=c.split(",");if(e.length>1)c=e[0];return Ca(c,"\"'")};var zb=document,A=navigator,B=window;
function Ab(){var a=zb.cookie,b=Math.round((new Date).getTime()/1000),c=B.google_analytics_domain_name,d=typeof c=="undefined"?Bb("auto"):Bb(c),e=a.indexOf("__utma="+d+".")>-1,f=a.indexOf("__utmb="+d)>-1,j=a.indexOf("__utmc="+d)>-1,i,l={};if(e){i=a.split("__utma="+d+".")[1].split(";")[0].split(".");l.sid=f&&j?i[3]+"":B&&B.gaGlobal&&B.gaGlobal.sid?B.gaGlobal.sid:b+"";l.vid=i[0]+"."+i[1];l.from_cookie=m}else{l.sid=B&&B.gaGlobal&&B.gaGlobal.sid?B.gaGlobal.sid:b+"";l.vid=B&&B.gaGlobal&&B.gaGlobal.vid?
B.gaGlobal.vid:(Cb()^Db()&2147483647)+"."+b;l.from_cookie=g}l.dh=d;l.hid=B&&B.gaGlobal&&B.gaGlobal.hid?B.gaGlobal.hid:Cb();return B.gaGlobal=l}function Cb(){return Math.round(Math.random()*2147483647)}
function Db(){var a=zb.cookie?zb.cookie:"",b=B.history.length,c,d,e=[A.appName,A.version,A.language?A.language:A.browserLanguage,A.platform,A.userAgent,A.javaEnabled()?1:0].join("");if(B.screen)e+=B.screen.width+"x"+B.screen.height+B.screen.colorDepth;else if(B.java){d=java.awt.Toolkit.getDefaultToolkit().getScreenSize();e+=d.screen.width+"x"+d.screen.height}e+=a;e+=zb.referrer?zb.referrer:"";c=e.length;for(;b>0;)e+=b--^c++;return Eb(e)}
function Eb(a){var b=1,c=0,d,e;if(!(a==undefined||a=="")){b=0;d=a.length-1;for(;d>=0;d--){e=a.charCodeAt(d);b=(b<<6&268435455)+e+(e<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function Bb(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=zb.domain;if("www."==a.substring(0,4))a=a.substring(4,a.length)}return Eb(a.toLowerCase())};var C=function(){};C.prototype.va=g;C.prototype.dispose=function(){if(!this.va){this.va=m;this.b()}};C.prototype.b=function(){};var Fb=function(a){if(/^\s*$/.test(a))return g;var b=/\\["\\\/bfnrtu]/g,c=/"[^"\\\n\r\u2028\u2029\x00-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,d=/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,e=/^[\],:{}\s\u2028\u2029]*$/;return e.test(a.replace(b,"@").replace(c,"]").replace(d,""))},Gb=function(a){String(a);if(Fb(a))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};var D=function(){};D.prototype.serialize=function(a){var b=[];this.ga(a,b);return b.join("")};
D.prototype.ga=function(a,b){switch(typeof a){case "string":this.Ia(a,b);break;case "number":this.Eb(a,b);break;case "boolean":b.push(a);break;case "undefined":b.push("null");break;case "object":if(a==h){b.push("null");break}if(s(a)=="array"){this.Db(a,b);break}this.Fb(a,b);break;case "function":break;default:throw Error("Unknown type: "+typeof a);}};
var Hb={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},Ib=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;D.prototype.Ia=function(a,b){b.push('"',a.replace(Ib,function(c){if(c in Hb)return Hb[c];var d=c.charCodeAt(0),e="\\u";if(d<16)e+="000";else if(d<256)e+="00";else if(d<4096)e+="0";return Hb[c]=e+d.toString(16)}),'"')};D.prototype.Eb=function(a,b){b.push(isFinite(a)&&!isNaN(a)?a:"null")};
D.prototype.Db=function(a,b){var c=a.length;b.push("[");var d="",e=0;for(;e<c;e++){b.push(d);this.ga(a[e],b);d=","}b.push("]")};D.prototype.Fb=function(a,b){b.push("{");var c="";for(var d in a)if(a.hasOwnProperty(d)){var e=a[d];if(typeof e!="function"){b.push(c);this.Ia(d,b);b.push(":");this.ga(e,b);c=","}}b.push("}")};var E="SETUP_ACK",F={},Kb=function(a,b){var c=b||Jb,d=c.length,e="";for(;a-- >0;)e+=c.charAt(Math.floor(Math.random()*d));return e},Jb="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";var G=function(){};u(G,C);G.prototype.f=0;var H=function(a){this.a=a;this.Q=[];this.Pb=t(this.Za,this)};u(H,G);H.prototype.f=2;H.prototype.ca=g;H.prototype.Gb=0;H.prototype.connect=function(){if(this.a.s()==0){this.l=this.a.t;this.l.XPC_toOuter=t(this.za,this)}else this.ma()};
H.prototype.ma=function(){var a=m;try{if(!this.l)this.l=window.frameElement;if(this.l&&this.l.XPC_toOuter){this.Da=this.l.XPC_toOuter;this.l.XPC_toOuter.XPC_toInner=t(this.za,this);a=g;this.send("tp",E);this.a.m()}}catch(b){}if(a){if(!this.Ma)this.Ma=t(this.ma,this);window.setTimeout(this.Ma,100)}};H.prototype.H=function(a){if(this.a.s()==0&&!this.a.g()&&a==E){this.Da=this.l.XPC_toOuter.XPC_toInner;this.a.m()}else throw Error("Got unexpected transport message.");};
H.prototype.za=function(a,b){if(!this.ca&&this.Q.length==0)this.a.j(a,b);else{this.Q.push({serviceName:a,payload:b});if(this.Q.length==1)this.Gb=window.setTimeout(this.Pb,1)}};H.prototype.Za=function(){for(;this.Q.length;){var a=this.Q.shift();this.a.j(a.serviceName,a.payload)}};H.prototype.send=function(a,b){this.ca=m;this.Da(a,b);this.ca=g};H.prototype.b=function(){H.o.b.call(this);this.l=this.Da=h};var I=function(a){this.a=a;this.R=this.a.e.ppu;this.Rb=this.a.e.lpu;this.ea=[]},Lb,Mb;u(I,G);I.prototype.f=4;I.prototype.fa=0;I.prototype.w=g;I.prototype.O=g;var Nb="googlexpc";I.prototype.M=function(){return Nb+"_"+this.a.name+"_msg"};I.prototype.L=function(){return Nb+"_"+this.a.name+"_ack"};I.prototype.connect=function(){if(!this.O){this.Sa();this.O=m}this.Oa()};I.prototype.Sa=function(){var a=this.M();this.D=this.W(a);this.Ba=window.frames[a];a=this.L();this.p=this.W(a);this.U=window.frames[a]};
I.prototype.W=function(a){var b=document.createElement("iframe"),c=b.style;c.position="absolute";c.top="-10px";c.left="10px";c.width="1px";c.height="1px";b.name=a;b.id=b.name;b.src=this.R+"#INITIAL";document.body.appendChild(b);return b};I.prototype.ob=function(){this.a.name=Kb(10);this.sa();this.O=g;this.Tb=this.W(Nb+"_reconnect_"+this.a.name)};
I.prototype.tb=function(){var a=this.a.h.frames,b=a.length,c=0;for(;c<b;c++){var d;try{if(a[c]&&a[c].name)d=a[c].name}catch(e){}if(!!d){var f=d.split("_");if(f.length==3&&f[0]==Nb&&f[1]=="reconnect"){this.a.name=f[2];this.sa();this.O=g;break}}}};I.prototype.sa=function(){if(this.D){this.D.parentNode.removeChild(this.D);this.Ba=this.D=h}if(this.p){this.p.parentNode.removeChild(this.p);this.U=this.p=h}};
I.prototype.Oa=function(){if(this.Aa(this.M())&&this.Aa(this.L())){this.qb=new Ob(this,this.a.h.frames[this.M()],t(this.wb,this));this.ja=new Ob(this,this.a.h.frames[this.L()],t(this.vb,this));this.pa()}else{if(this.a.s()==1&&!this.Tb)this.ob();else this.a.s()==0&&this.tb();window.setTimeout(t(this.connect,this),100)}};I.prototype.Aa=function(a){try{var b=this.a.h.frames[a];if(!b||b.location.href.indexOf(this.Rb)!=0)return g}catch(c){return g}return m};
I.prototype.pa=function(){var a=this.a.h.frames;if(a[this.L()]&&a[this.M()]){this.rb=new Pb(this.R,this.Ba);this.T=new Pb(this.R,this.U);window.setTimeout(t(function(){this.rb.send("SETUP");this.w=this.Wb=m},this),100)}else{if(!this.Pa)this.Pa=t(this.pa,this);window.setTimeout(this.Pa,100)}};I.prototype.oa=function(){if(this.Cb&&this.Sb){this.a.m();if(this.K){var a=0,b;for(;a<this.K.length;a++){b=this.K[a];this.a.j(b.service,b.payload)}delete this.K}}};
I.prototype.wb=function(a){if(a=="SETUP"){if(!!this.T){this.T.send(E);this.Cb=m;this.oa()}}else if(this.a.g()||this.Cb){var b=a.indexOf("|"),c=a.substring(0,b),d=a.substring(b+1);b=c.indexOf(",");if(b==-1){var e=c;this.T.send("ACK:"+e);this.ta(d)}else{var e=c.substring(0,b);this.T.send("ACK:"+e);var f=c.substring(b+1).split("/");f[0]=parseInt(f[0],10);f[1]=parseInt(f[1],10);if(f[0]==1)this.Ea=[];this.Ea.push(d);if(f[0]==f[1]){this.ta(this.Ea.join(""));delete this.Ea}}}};
I.prototype.vb=function(a){if(a==E){this.w=g;this.Sb=m;this.oa()}else if(this.a.g())if(!!this.w){var b=parseInt(a.split(":")[1],10);if(b==this.fa){this.w=g;this.Ha()}}};I.prototype.Ha=function(){if(!(this.w||!this.ea.length)){var a=this.ea.shift();++this.fa;this.rb.send(this.fa+a);this.w=m}};I.prototype.ta=function(a){var b=a.indexOf(":"),c=a.substr(0,b),d=a.substring(b+1);this.a.g()?this.a.j(c,d):(this.K||(this.K=[])).push({service:c,payload:d})};I.prototype.J=3800;
I.prototype.send=function(a,b){var c=a+":"+b;if(!w||b.length<=this.J)this.ea.push("|"+c);else{var d=b.length,e=Math.ceil(d/this.J),f=0,j=1;for(;f<d;){this.ea.push(","+j+"/"+e+"|"+c.substr(f,this.J));j++;f+=this.J}}this.Ha()};I.prototype.b=function(){I.o.b.call(this);var a=Qb;za(a,this.qb);za(a,this.ja);this.qb=this.ja=h;mb(this.D);mb(this.p);this.Ba=this.U=this.D=this.p=h};
var Qb=[],Sb=function(){var a=g;try{var b=0,c=Qb.length;for(;b<c;b++)a=a||Qb[b].receive()}catch(d){Qb[b].c.a.sb();if(!Qb.length)return}var e=wa();if(a)Lb=e;var f=e-Lb<1000?10:100;Mb=window.setTimeout(Rb,f)},Rb=t(Sb,I),Tb=function(){Lb=wa();Mb&&window.clearTimeout(Mb);Mb=window.setTimeout(Rb,10)},Pb=function(a,b){this.R=a;this.Bb=b;this.ra=0};Pb.prototype.send=function(a){this.ra=++this.ra%2;var b=this.R+"#"+this.ra+encodeURIComponent(a);try{if(x)this.Bb.location.href=b;else this.Bb.location.replace(b)}catch(c){}Tb()};
var Ob=function(a,b,c){this.c=a;this.xb=b;this.Lb=c;this.Xa=this.xb.location.href.split("#")[0]+"#INITIAL";Qb.push(this);Tb()};Ob.prototype.receive=function(){var a=this.xb.location.href;if(a!=this.Xa){this.Xa=a;var b=a.split("#")[1];if(b){b=b.substr(1);this.Lb(decodeURIComponent(b))}return m}else return g};var J=function(a,b){C.call(this);this.pb=b;this.r=[];this.Va(a)};u(J,C);J.prototype.X=h;J.prototype.Y=h;J.prototype.G=function(a){this.X=a};J.prototype.Ka=function(a){this.Y=a};J.prototype.k=function(){if(this.r.length)return this.r.pop();return this.qa()};J.prototype.v=function(a){this.r.length<this.pb?this.r.push(a):this.ua(a)};J.prototype.Va=function(a){if(a>this.pb)throw Error("[goog.structs.SimplePool] Initial cannot be greater than max");var b=0;for(;b<a;b++)this.r.push(this.qa())};
J.prototype.qa=function(){return this.X?this.X():{}};J.prototype.ua=function(a){if(this.Y)this.Y(a);else if(qa(a.dispose))a.dispose();else for(var b in a)delete a[b]};J.prototype.b=function(){J.o.b.call(this);var a=this.r;for(;a.length;)this.ua(a.pop());delete this.r};var L=function(a,b){this.type=a;this.currentTarget=this.target=b};u(L,C);L.prototype.b=function(){delete this.type;delete this.target;delete this.currentTarget};L.prototype.F=g;L.prototype.da=m;L.prototype.stopPropagation=function(){this.F=m};L.prototype.preventDefault=function(){this.da=g};var M=function(a,b){a&&this.init(a,b)};u(M,L);M.prototype.type=h;M.prototype.target=h;M.prototype.relatedTarget=h;M.prototype.offsetX=0;M.prototype.offsetY=0;M.prototype.clientX=0;M.prototype.clientY=0;M.prototype.screenX=0;M.prototype.screenY=0;M.prototype.button=0;M.prototype.keyCode=0;M.prototype.charCode=0;M.prototype.ctrlKey=g;M.prototype.altKey=g;M.prototype.shiftKey=g;M.prototype.metaKey=g;M.prototype.i=h;
M.prototype.init=function(a,b){this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;this.relatedTarget=a.relatedTarget?a.relatedTarget:this.type=="mouseover"?a.fromElement:this.type=="mouseout"?a.toElement:h;this.offsetX=typeof a.layerX=="number"?a.layerX:a.offsetX;this.offsetY=typeof a.layerY=="number"?a.layerY:a.offsetY;this.clientX=typeof a.clientX=="number"?a.clientX:a.pageX;this.clientY=typeof a.clientY=="number"?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||
0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(this.type=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.i=a;delete this.da;delete this.F};M.prototype.stopPropagation=function(){this.F=m;if(this.i.stopPropagation)this.i.stopPropagation();else this.i.cancelBubble=m};
M.prototype.preventDefault=function(){this.da=g;if(this.i.preventDefault)this.i.preventDefault();else{this.i.returnValue=g;try{this.i.keyCode=-1}catch(a){}}};M.prototype.fb=function(){return this.i};M.prototype.b=function(){M.o.b.call(this);this.i=h};var O=function(){},Ub=0;O.prototype.aa=h;O.prototype.listener=h;O.prototype.proxy=h;O.prototype.src=h;O.prototype.type=h;O.prototype.capture=h;O.prototype.handler=h;O.prototype.key=0;O.prototype.removed=g;O.prototype.na=g;
O.prototype.init=function(a,b,c,d,e,f){if(qa(a))this.aa=m;else if(a&&a.handleEvent&&qa(a.handleEvent))this.aa=g;else throw Error("Invalid listener argument");this.listener=a;this.proxy=b;this.src=c;this.type=d;this.capture=!!e;this.handler=f;this.na=g;this.key=++Ub;this.removed=g};O.prototype.handleEvent=function(a){if(this.aa)return this.listener.call(this.handler||this.src,a);return this.listener.handleEvent.call(this.listener,a)};var Vb={},P={},Wb={},Xb=new J(0,600);Xb.G(function(){return{q:0}});Xb.Ka(function(a){a.q=0});var Q=new J(0,600);Q.G(function(){return[]});Q.Ka(function(a){a.length=0;delete a.P;delete a.Ca});var $b=new J(0,600);$b.G(function(){var a=function(b){return ac.call(a.src,a.key,b)};return a});var bc=function(){return new O},cc=new J(0,600);cc.G(bc);
var dc=function(){return new M},ec=function(){var a=h;if(w){a=new J(0,600);a.G(dc)}return a},fc=ec(),gc="on",hc={},ic=function(a,b,c,d,e){if(b)if(s(b)=="array"){var f=0;for(;f<b.length;f++)ic(a,b[f],c,d,e);return h}else{var j=!!d,i=P;b in i||(i[b]=Xb.k());i=i[b];if(!(j in i)){i[j]=Xb.k();i.q++}i=i[j];var l=ua(a),k,o;if(i[l]){k=i[l];var f=0;for(;f<k.length;f++){o=k[f];if(o.listener==c&&o.handler==e){if(o.removed)break;return k[f].key}}}else{i[l]=Q.k();k=i[l];i.q++}var p=$b.k();p.src=a;o=cc.k();o.init(c,
p,a,b,j,e);var q=o.key;p.key=q;k.push(o);Vb[q]=o;Wb[l]||(Wb[l]=Q.k());Wb[l].push(o);if(a.addEventListener){if(a==r||!a.Ob)a.addEventListener(b,p,j)}else a.attachEvent(jc(b),p);return q}else throw Error("Invalid event type");},kc=function(a,b,c,d,e){if(s(b)=="array"){var f=0;for(;f<b.length;f++)kc(a,b[f],c,d,e);return h}var j=!!d,i=lc(a,b,j);if(!i)return g;var f=0;for(;f<i.length;f++)if(i[f].listener==c&&i[f].capture==j&&i[f].handler==e)return mc(i[f].key);return g},mc=function(a){if(!Vb[a])return g;
var b=Vb[a];if(b.removed)return g;var c=b.src,d=b.type,e=b.proxy,f=b.capture;if(c.removeEventListener){if(c==r||!c.Ob)c.removeEventListener(d,e,f)}else c.detachEvent&&c.detachEvent(jc(d),e);var j=ua(c),i=P[d][f][j];if(Wb[j]){var l=Wb[j];za(l,b);l.length==0&&delete Wb[j]}b.removed=m;i.Ca=m;nc(d,f,j,i);delete Vb[a];return m},nc=function(a,b,c,d){if(!d.P)if(d.Ca){var e=0,f=0;for(;e<d.length;e++)if(d[e].removed)cc.v(d[e]);else{if(e!=f)d[f]=d[e];f++}d.length=f;d.Ca=g;if(f==0){Q.v(d);delete P[a][b][c];
P[a][b].q--;if(P[a][b].q==0){Xb.v(P[a][b]);delete P[a][b];P[a].q--}if(P[a].q==0){Xb.v(P[a]);delete P[a]}}}},lc=function(a,b,c){var d=P;if(b in d){d=d[b];if(c in d){d=d[c];var e=ua(a);if(d[e])return d[e]}}return h},jc=function(a){if(a in hc)return hc[a];return hc[a]=gc+a},pc=function(a,b,c,d){var e=1,f=P;if(b in f){f=f[b];if(c in f){f=f[c];var j=ua(a);if(f[j]){var i=f[j];if(i.P)i.P++;else i.P=1;try{var l=i.length,k=0;for(;k<l;k++){var o=i[k];if(o&&!o.removed)e&=oc(o,d)!==g}}finally{i.P--;nc(b,c,j,
i)}}}}return Boolean(e)},oc=function(a,b){var c=a.handleEvent(b);a.na&&mc(a.key);return c},ac=function(a,b){if(!Vb[a])return m;var c=Vb[a],d=c.type,e=P;if(!(d in e))return m;e=e[d];var f;if(w){var j=b||na("window.event"),i=m in e;if(i){if(j.keyCode<0||j.returnValue!=undefined)return m;qc(j)}ua(c.src);var l=fc.k();l.init(j,this);f=m;try{if(i){var k=Q.k(),o=l.currentTarget;for(;o;o=o.parentNode)k.push(o);var p=k.length-1;for(;!l.F&&p>=0;p--){l.currentTarget=k[p];f&=pc(k[p],d,m,l)}var p=0;for(;!l.F&&
p<k.length;p++){l.currentTarget=k[p];f&=pc(k[p],d,g,l)}}else f=oc(c,l)}finally{if(k){k.length=0;Q.v(k)}l.dispose();fc.v(l)}return f}var q=new M(b,this);try{f=oc(c,q)}finally{q.dispose()}return f},qc=function(a){var b=g;if(a.keyCode==0)try{a.keyCode=-1;return}catch(c){b=m}if(b||a.returnValue==undefined)a.returnValue=m};var R=function(a){this.a=a;this.Qb=this.a.e.pru;this.ub=this.a.e.ifrid;x&&rc()};u(R,G);if(x)var sc=[],tc=0,rc=function(){tc||(tc=window.setTimeout(function(){uc()},1000))},uc=function(a){var b=wa(),c=a||3000;for(;sc.length&&b-sc[0].timestamp>=c;){var d=sc.shift().iframeElement;mb(d)}tc=window.setTimeout(vc,1000)},vc=function(){uc()};R.prototype.f=3;R.prototype.connect=function(){this.send("tp","SETUP")};R.prototype.H=function(a){if(a=="SETUP"){this.send("tp",E);this.a.m()}else a==E&&this.a.m()};
R.prototype.send=function(a,b){if(w){var c=document.createElement("div");c.innerHTML='<iframe onload="this.xpcOnload()"></iframe>';var d=c.childNodes[0];d.xpcOnload=wc}else{var d=document.createElement("iframe");x?sc.push({timestamp:wa(),iframeElement:d}):ic(d,"load",wc)}var e=d.style;e.visibility="hidden";d.style.height="0px";e.width=d.style.height;e.position="absolute";var f=this.Qb;f+="#"+this.a.name;if(this.ub)f+=","+this.ub;f+="|"+a+":"+encodeURIComponent(b);d.src=f;document.body.appendChild(d)};
var wc=function(){mb(this);this.xpcOnload=h};window.xpcRelay=function(a,b){var c=b.indexOf(":"),d=b.substring(0,c),e=b.substring(c+1);F[a].j(d,decodeURIComponent(e))};R.prototype.b=function(){R.o.b.call(this);x&&uc(0)};var S=function(a,b){this.a=a;this.ba=b||"*"};u(S,G);S.prototype.f=1;var xc=g,zc=function(){if(!xc){ic(window.postMessage?window:document,"message",yc,g,S);xc=m}},yc=function(a){var b=a.fb().data,c=b.indexOf("|"),d=b.indexOf(":");if(c==-1||d==-1)return g;var e=b.substring(0,c),f=b.substring(c+1,d),j=b.substring(d+1),i=F[e];if(i){i.j(f,j);return m}for(var l in F){var k=F[l];if(k.s()==1&&!k.g()&&f=="tp"&&j=="SETUP"){k.name=e;F[e]=k;F[l]=h;k.j(f,j);return m}}return g};
S.prototype.H=function(a){switch(a){case "SETUP":if(!this.Ub){this.Ub=m;this.send("tp",E)}break;case E:this.a.m();break}};S.prototype.connect=function(){zc();this.V()};S.prototype.V=function(){if(!this.a.g()){this.send("tp","SETUP");window.setTimeout(t(this.V,this),100)}};S.prototype.send=function(a,b){var c=this.a.h;if(!!c){var d=c.postMessage?c:c.document;this.send=function(e,f){d.postMessage(this.a.name+"|"+e+":"+f,this.ba)};this.send(a,b)}};
S.prototype.b=function(){S.o.b.call(this);kc(window.postMessage?window:document,"message",yc,g,S)};var T=function(a){this.a=a;this.Na=a.at||"";this.Ab=a.rat||"";Ac();this[Bc]=this.N;this[Cc]=this.Ua};u(T,G);
var Dc="GCXPC____NIXVBS_wrapper",Ec="GCXPC____NIXVBS_get_wrapper",Bc="GCXPC____NIXJS_handle_message",Cc="GCXPC____NIXJS_create_channel",Fc="GCXPC____NIXVBS_container",Ac=function(){if(!window.nix_setup_complete){var a="Class "+Dc+"\n Private m_Transport\nPrivate m_Auth\nPublic Sub SetTransport(transport)\nIf isEmpty(m_Transport) Then\nSet m_Transport = transport\nEnd If\nEnd Sub\nPublic Sub SetAuth(auth)\nIf isEmpty(m_Auth) Then\nm_Auth = auth\nEnd If\nEnd Sub\nPublic Function GetAuthToken()\n GetAuthToken = m_Auth\nEnd Function\nPublic Sub SendMessage(service, payload)\n Call m_Transport."+Bc+
"(service, payload)\nEnd Sub\nPublic Sub CreateChannel(channel)\n Call m_Transport."+Cc+"(channel)\nEnd Sub\nPublic Sub "+Fc+"()\n End Sub\nEnd Class\n Function "+Ec+"(transport, auth)\nDim wrap\nSet wrap = New "+Dc+"\nwrap.SetTransport transport\nwrap.SetAuth auth\nSet "+Ec+" = wrap\nEnd Function";try{window.execScript(a,"vbscript");window.nix_setup_complete=m}catch(b){}}};T.prototype.f=6;T.prototype.u=g;T.prototype.n=h;T.prototype.connect=function(){this.a.s()==0?this.la():this.ka()};
T.prototype.la=function(){if(!this.u){var a=this.a.t;try{a.contentWindow.opener=window[Ec](this,this.Na);this.u=m}catch(b){}this.u||window.setTimeout(t(this.la,this),100)}};T.prototype.ka=function(){if(!this.u){try{var a=window.opener;if(a&&Fc in a){this.n=a;var b=this.n.GetAuthToken();if(b!=this.Ab)return;this.n.CreateChannel(window[Ec](this,this.Na));this.u=m;this.a.m()}}catch(c){return}this.u||window.setTimeout(t(this.ka,this),100)}};
T.prototype.Ua=function(a){this.n=a;var b=this.n.GetAuthToken();b!=this.Ab||this.a.m()};T.prototype.N=function(a,b){function c(){this.a.j(a,b)}window.setTimeout(t(c,this),1)};T.prototype.send=function(a,b){this.n.SendMessage(a,b)};T.prototype.b=function(){T.o.b.call(this);this.n=h};var U=function(a){C.call(this);this.e=a;this.name=this.e.cn||Kb(10);this.Ja={};F[this.name]=this;ic(window,"unload",Gc)};u(U,C);U.prototype.c=h;U.prototype.ha=1;U.prototype.g=function(){return this.ha==2};U.prototype.h=h;U.prototype.t=h;U.prototype.La=function(a){this.h=a};U.prototype.ab=function(){var a;if(qa(document.postMessage)||qa(window.postMessage)||w&&window.postMessage)a=1;else if(Ra)a=2;else if(w&&this.e.pru)a=3;else if(w)a=6;else if(this.e.lpu&&this.e.ppu)a=4;return a};
U.prototype.Wa=function(){if(!this.c){this.e.tp||(this.e.tp=this.ab());switch(this.e.tp){case 1:this.c=new S(this,this.e.ph);break;case 6:this.c=new T(this);break;case 2:this.c=new H(this);break;case 3:this.c=new R(this);break;case 4:this.c=new I(this);break}if(!this.c)throw Error("CrossPageChannel: No suitable transport found!");}};U.prototype.Ya=g;U.prototype.Ra=g;
U.prototype.connect=function(a){this.Nb=a||pa;if(this.Ya)this.Ra=m;else{if(this.e.ifrid)this.t=typeof this.e.ifrid=="string"?document.getElementById(this.e.ifrid):this.e.ifrid;if(this.t){var b=this.t.contentWindow;b||(b=window.frames[this.e.ifrid]);this.La(b)}if(!this.h)if(window==top)throw Error("CrossPageChannel: Can't connect, peer window-object not set.");else this.La(window.parent);this.Wa();this.c.connect()}};U.prototype.close=function(){if(!!this.g()){this.ha=3;this.c.dispose();this.c=h}};
U.prototype.m=function(){if(!this.g()){this.ha=2;this.Nb()}};U.prototype.sb=function(){this.close()};U.prototype.zb=function(a,b,c){this.Ja[a]={name:a,callback:b,jsonEncoded:!!c}};U.prototype.send=function(a,b){if(!!this.g())if(this.h.closed)this.close();else{if(ra(b))b=(new D).serialize(b);this.c.send(a,b)}};U.prototype.j=function(a,b){if(!a||a=="tp")this.c.H(b);else if(this.g()){var c=this.Ja[a];if(c){if(c.jsonEncoded)try{b=Gb(b)}catch(d){return}c.callback(b)}}};
U.prototype.s=function(){return window.parent==this.h?1:0};U.prototype.b=function(){U.o.b.call(this);this.close();this.t=this.h=h;delete this.Ja;F[this.name]=h};var Gc=function(){for(var a in F){var b=F[a];b&&b.dispose()}};var Hc=function(a){var b=a||document.location.protocol+"//"+document.location.host;return b+"/robots.txt"};var V=function(a,b){this.A=a.width;this.z=a.height;this.Mb=b;this.ba=this.hb(a.src,document);this.$=g;this.d=a;this.nb(this.jb())};V.prototype.jb=function(){var a={};a.ifrid=this.d.id;a.pu=this.d.src;a.ph=this.ba;a.cn=this.Mb;a.ppu=Hc(this.ba);a.lpu=Hc();return a};V.prototype.nb=function(a){this.a=new U(a);this.a.zb("expandable_ad",t(this.N,this));this.a.connect(function(){});window.setTimeout(t(this.lb,this),30000)};
V.prototype.lb=function(){if(this.a&&!this.a.g()){this.a.c.connect=function(){};if(this.a.c.f==1)this.a.c.V=function(){};if(this.a.c.f==4)this.a.c.Vb=function(){};this.a.c.dispose();this.a.dispose()}};V.prototype.hb=function(a,b){var c=a.indexOf("//"),d=c>0,e=d?a.substring(0,c):b.location.protocol,f=d?a.substring(c+2):b.location.host,j=f.indexOf("/");if(j<0)j=f.indexOf("?");if(d&&j>0)f=f.substring(0,j);return e+"//"+f};
V.prototype.N=function(a){var b=a.split("_"),c=b[0];if(c=="expand")this.mb(b);else c=="collapse"&&this.kb()};V.prototype.Ga=function(a){this.a.send("expandable_ad",a)};V.prototype.mb=function(a){if(!this.$){var b,c,d=0;for(;d<a.length;++d){var e=a[d].charAt(0);if(e=="w")b=parseInt(a[d].substring(1),10);else if(e=="h")c=parseInt(a[d].substring(1),10)}var f=this.$a(b,c);this.cb(b,c,f);this.Ga("ok_expand_w"+b+"_h"+c+"_d"+f)}};
V.prototype.kb=function(){if(!!this.$){this.Qa();this.Ga("ok_collapse_w"+this.A+"_h"+this.z)}};V.prototype.Qa=function(){this.d.style.width=this.A+"px";this.d.style.height=this.z+"px";this.d.style.left="0";this.d.style.top="0";this.d.style.zIndex=h;this.d.parentNode.style.zIndex=h;this.d.parentNode.parentNode.style.zIndex=h;this.$=g};
V.prototype.cb=function(a,b,c){this.d.style.position="absolute";this.d.style.width=a+"px";this.d.style.height=b+"px";this.d.style.zIndex=9999;this.d.parentNode.style.zIndex=9999;this.d.parentNode.parentNode.style.zIndex=9999;if(a>this.A&&(c==0||c==3))this.d.style.left="-"+(a-this.A)+"px";if(b>this.z&&(c==1||c==0))this.d.style.top="-"+(b-this.z)+"px";this.$=m};
V.prototype.$a=function(a,b){var c=xb(this.d),d=kb(window),e=a-this.A,f=b-this.z,j=c.y,i=f>j,l=d.height-(c.y+this.z),k=i||l>=j,o=c.x,p=e>o,q=d.width-(c.x+this.A),K=p||q>=o,N=0;if(k&&K)N=2;else if(k&&!K)N=3;else if(!k&&K)N=1;else if(!k&&!K)N=0;return N};
var Ic=function(){},Lc=function(a,b,c,d,e){if(!a||!b||c<=0||d<=0)return h;var f=Kb(10);b=Jc(b,c,d,f);var j=Kc(a,b,c,d,e);return new V(j,f)},Jc=function(a,b,c,d){var e=hb().wa();return a+(a.indexOf("?")==-1?"?":"&")+"w="+b+"&h="+c+"&xpc="+d+"&p="+escape(e.location.protocol+"//"+e.location.host)},Kc=function(a,b,c,d,e){var f="border:none;height:"+d+"px;margin:0;padding:0;position:relative;visibility:visible;width:"+c+"px",j='<ins style="display:inline-table;'+f+'"><ins style="display:block;'+f+'"><iframe allowtransparency=true frameborder=0 height='+
d+" hspace=0 id="+a+' marginheight=0 marginwidth=0 name=google_ads_frame scrolling=no src="'+b+'" style="left:0;position:absolute;top:0" vspace=0 width='+c+"></iframe></ins></ins>",i=hb(),l=i.ya(e);if(l)l.innerHTML=j;else i.wa().write(j);return i.ya(a)};xa("ExpandableAdSlot",V);xa("ExpandableAdSlotFactory",Ic);var W="";function Mc(a){if(a){if(W!="")W+=",";W+=a}}var Nc=g,Oc=ha("true",g);function Pc(a){return a!=h?'"'+a+'"':'""'}function fa(a){return typeof encodeURIComponent=="function"?encodeURIComponent(a):escape(a)}function X(a,b){if(a&&b)window.google_ad_url+="&"+a+"="+b}function Y(a){var b=window,c=ea(a),d=b[a];X(c,d)}function Z(a,b){b!=h&&X(a,fa(b))}function $(a){var b=window,c=ea(a),d=b[a];Z(c,d)}
function Qc(a,b){var c=window,d=ea(a),e=c[a];if(d&&e&&typeof e=="object")e=e[b%e.length];X(d,e)}function Rc(a){var b=a.screen,c=navigator.javaEnabled(),d=-(new Date).getTimezoneOffset();if(b){X("u_h",b.height);X("u_w",b.width);X("u_ah",b.availHeight);X("u_aw",b.availWidth);X("u_cd",b.colorDepth)}X("u_tz",d);X("u_his",history.length);X("u_java",c);navigator.plugins&&X("u_nplug",navigator.plugins.length);navigator.mimeTypes&&X("u_nmime",navigator.mimeTypes.length)}
function Sc(a){if(!!a.google_enable_first_party_cookie){if(a._GA_googleCookieHelper==h)a._GA_googleCookieHelper=new n;if(!a._google_cookie_fetched){a._google_cookie_fetched=m;a._GA_googleCookieHelper.db(Tc(a.google_ad_client))}}}function Tc(a){if(a){a=a.toLowerCase();if(a.substring(0,3)!="ca-")a="ca-"+a}return a}function Uc(a){if(a){a=a.toLowerCase();if(a.substring(0,9)!="dist-aff-")a="dist-aff-"+a}return a}function Vc(a){var b="google_unique_id";if(a[b])++a[b];else a[b]=1;return a[b]}
function Wc(){var a=w&&y("6")&&!y("8"),b=Ra&&y("1.8.1"),c=x&&y("525");if(Ya&&(a||b||c))return m;else if(Xa&&(c||b))return m;else if(Za&&b)return m;return g}function Xc(a,b){var c=a.google_allow_expandable_ads;if(c!=h&&c==g||!b.body||a.google_ad_output!="html"||Yc(a,b)||Zc(a)||$c(a.google_ad_format)||isNaN(a.google_ad_height)||isNaN(a.google_ad_width)||!Wc())return g;return m}
function ad(){var a=Math.random(),b=ga("0.03",0.03),c=2*b;if(a<b)return"30143019";if(a<c)return"30143020";return""}function bd(){var a=Math.random(),b=ga("0",0.03),c=2*b;if(a<b)return"30143021";if(a<c)return"30143022";return""}function cd(){var a=Math.random(),b=ga("0.03",0.02),c=2*b;if(a<b)return"6083028";if(a<c)return"6083029";return""}function dd(a){a.google_allow_expandable_ads=g;a.google_expandable_iframe=g}
function ed(a,b,c,d){var e=Vc(a);c=c.substring(0,1992);c=c.replace(/%\w?$/,"");var f="script";if((a.google_ad_output=="js"||a.google_ad_output=="json_html")&&(a.google_ad_request_done||a.google_radlink_request_done))b.write("<"+f+' language="JavaScript1.1" src='+Pc(fd(c))+"></"+f+">");else if(a.google_ad_output=="html")if(gd(a)){var j=a.google_container_id||d||h;a["google_expandable_ad_slot"+e]=Lc("google_ads_frame"+e,fd(c),a.google_ad_width,a.google_ad_height,j)}else{var i='<iframe name="google_ads_frame" width='+
Pc(a.google_ad_width)+" height="+Pc(a.google_ad_height)+" frameborder="+Pc(a.google_ad_frameborder)+" src="+Pc(fd(c))+' marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>';i=hd(a.google_ad_width,a.google_ad_height,i);a.google_container_id?id(a.google_container_id,b,i):b.write(i)}else a.google_ad_output=="textlink"&&b.write("<"+f+' language="JavaScript1.1" src='+Pc(fd(c))+"></"+f+">")}
function gd(a){if(!Nc)return g;var b=W.indexOf("30143020")!=-1,c=W.indexOf("30143019")!=-1,d=a.google_expandable_iframe;return Oc&&!c||b||d}function jd(a){var b=ha("false",g);return b&&a.indexOf("30143021")==-1||a.indexOf("30143022")!=-1}
function hd(a,b,c){var d=jd(W);if(Nc&&d){var e="border:none;height:"+b+"px;margin:0;padding:0;position:relative;visibility:visible;width:"+a+"px";return'<ins style="display:inline-table;'+e+'"><ins style="display:block;'+e+'">'+c+"</ins></ins>"}return c}function kd(a){for(var b in ba)a[b]=h;for(var b in ca)b=="google_correlator"||(a[b]=h);for(var b in da)a[b]=h;a.google_allow_expandable_ads=h;a.google_container_id=h;a.google_expandable_iframe=h;a.google_tag_js_version=h}
function Zc(a){if(a.google_ad_format)return a.google_ad_format.indexOf("_0ads")>0;return a.google_ad_output!="html"&&a.google_num_radlinks>0}function $c(a){return a&&a.indexOf("_sdo")!=-1}
function ld(a){var b=h,c=window,d=document,e=aa,f=c.google_ad_format,j=md(c),i;if(c.google_cpa_choice!=b){c.google_ad_url=j+"/cpa/ads?";i=escape(Tc(c.google_ad_client));c.google_ad_region="_google_cpa_region_";Y("google_cpa_choice");if(typeof d.characterSet!="undefined")Z("oe",d.characterSet);else typeof d.charset!="undefined"&&Z("oe",d.charset)}else if($c(f)){c.google_ad_url=j+"/pagead/sdo?";i=escape(Uc(c.google_ad_client))}else{c.google_ad_url=j+"/pagead/ads?";i=escape(Tc(c.google_ad_client))}c.google_ad_url+=
"client="+i;Y("google_ad_host");Y("google_ad_host_tier_id");var l=c.google_num_slots_by_client,k=c.google_num_slots_by_channel,o=c.google_prev_ad_formats_by_region,p=c.google_prev_ad_slotnames_by_region;if(c.google_ad_region==b&&c.google_ad_section!=b)c.google_ad_region=c.google_ad_section;var q=c.google_ad_region==b?"":c.google_ad_region;if($c(f)){c.google_num_sdo_slots=c.google_num_sdo_slots?c.google_num_sdo_slots+1:1;if(c.google_num_sdo_slots>4)return g}else if(Zc(c)){c.google_num_0ad_slots=c.google_num_0ad_slots?
c.google_num_0ad_slots+1:1;if(c.google_num_0ad_slots>3)return g}else if(c.google_cpa_choice==b){c.google_num_ad_slots=c.google_num_ad_slots?c.google_num_ad_slots+1:1;if(c.google_num_slots_to_rotate){o[q]=b;p[q]=b;if(c.google_num_slot_to_show==b)c.google_num_slot_to_show=e%c.google_num_slots_to_rotate+1;if(c.google_num_slot_to_show!=c.google_num_ad_slots)return g}else if(c.google_num_ad_slots>6&&q=="")return g}X("dt",aa);Y("google_language");c.google_country?Y("google_country"):Y("google_gl");Y("google_region");
$("google_city");$("google_hints");Y("google_safe");Y("google_encoding");Y("google_last_modified_time");$("google_alternate_ad_url");Y("google_alternate_color");Y("google_skip");Y("google_targeting");var K=c.google_ad_client;if(l[K])l[K]+=1;else{l[K]=1;l.length+=1}if(o[q])if(!$c(f)){Z("prev_fmts",o[q].toLowerCase());l.length>1&&X("slot",l[K])}p[q]&&Z("prev_slotnames",p[q].toLowerCase());if(f&&!c.google_ad_slot){Z("format",f.toLowerCase());$c(f)||(o[q]=o[q]?o[q]+","+f:f)}if(c.google_ad_slot)p[q]=p[q]?
p[q]+","+c.google_ad_slot:c.google_ad_slot;Y("google_max_num_ads");X("output",c.google_ad_output);Y("google_adtest");Y("google_ad_callback");Y("google_ad_slot");$("google_correlator");c.google_new_domain_checked==1&&c.google_new_domain_enabled==0&&X("dblk",1);if(c.google_ad_channel){$("google_ad_channel");var N="",Yb=c.google_ad_channel.split(nd),db=0;for(;db<Yb.length;db++){var eb=Yb[db];if(k[eb])N+=eb+"+";else k[eb]=1}Z("pv_ch",N)}if(c.google_ad_host_channel){$("google_ad_host_channel");var vd=
od(c.google_ad_host_channel,c.google_viewed_host_channels);Z("pv_h_ch",vd)}c.google_enable_first_party_cookie&&Z("cookie",c._GA_googleCookieHelper.ib());$("google_page_url");Qc("google_color_bg",e);Qc("google_color_text",e);Qc("google_color_link",e);Qc("google_color_url",e);Qc("google_color_border",e);Qc("google_color_line",e);c.google_reuse_colors?X("reuse_colors",1):X("reuse_colors",0);Y("google_kw_type");$("google_kw");$("google_contents");Y("google_num_radlinks");Y("google_max_radlink_len");Y("google_rl_filtering");
Y("google_rl_mode");Y("google_rt");$("google_rl_dest_url");Y("google_num_radlinks_per_unit");Y("google_ad_type");Y("google_image_size");Y("google_ad_region");if(Nc=Xc(c,d))if(c.google_expandable_iframe===g)dd(c);else if(i in{"ca-pub-2944451727872625":1,"ca-pub-9483266128490610":1,"ca-pub-1955924717845427":1,"ca-pub-6664249124335298":1})c.google_expandable_iframe=m;else{if(!(c.google_expandable_iframe==m)){var oa=ad();Mc(oa);if(oa=="30143019"||oa==""&&!Oc)dd(c);if(!oa){oa=bd();Mc(oa)}}}else dd(c);
X("eid",W);var Zb=c.google_allow_expandable_ads;if(Zb!=h)Zb?X("ea","1"):X("ea","0");Y("google_feedback");$("google_referrer_url");$("google_page_location");X("frm",c.google_iframing);Y("google_bid");Y("google_ctr_threshold");Y("google_cust_age");Y("google_cust_gender");Y("google_cust_interests");Y("google_cust_id");Y("google_cust_job");Y("google_cust_u_url");Y("google_cust_l");Y("google_cust_lh");Y("google_cust_ch");Y("google_ed");Y("google_video_doc_id");Y("google_video_product_type");$("google_ui_features");
$("google_ui_version");$("google_tag_js_version");$("google_only_ads_with_video");$("google_only_pyv_ads");$("google_disable_video_autoplay");if(a){Z("ff",yb(a));var fb=wb(a),gb=kb();if(fb&&gb){Z("biw",gb.width);Z("bih",gb.height);Z("adx",fb.x);Z("ady",fb.y)}}Ab();X("ga_vid",c.gaGlobal.vid);X("ga_sid",c.gaGlobal.sid);X("ga_hid",c.gaGlobal.hid);X("ga_fc",c.gaGlobal.from_cookie);$("google_analytics_uacct");Y("google_ad_override");Y("google_flash_version");Rc(c);return m}
function od(a,b){var c=a.split("|"),d=-1,e=[],f=0;for(;f<c.length;f++){var j=c[f].split(nd);b[f]||(b[f]={});var i="",l=0;for(;l<j.length;l++){var k=j[l];if(!(k==""))if(b[f][k])i+="+"+k;else b[f][k]=1}i=i.slice(1);e[f]=i;if(i!="")d=f}var o="";if(d>-1){var f=0;for(;f<d;f++)o+=e[f]+"|";o+=e[d]}return o}
function pd(){var a=window,b=document;Sc(a);var c=cd();Mc(c);var d;if(c=="6083029"){var e="google_temp_span";d=a.google_container_id&&jb(a.google_container_id)||jb(e);if(!d&&!a.google_container_id){b.write("<span id="+e+"></span>");d=jb(e)}}var f=ld(d);d&&d.id==e&&mb(d);if(!!f){ed(a,b,a.google_ad_url);kd(a)}}function fd(a){var b=(new Date).getTime()-aa,c="&dtd="+(b<1000?b:"M");return a+c}function qd(){pd();return m}
function Yc(a,b){if(a.top.location==b.location)return g;var c=b.documentElement;if(a.google_ad_width&&a.google_ad_height){var d=1,e=1;if(a.innerHeight){d=a.innerWidth;e=a.innerHeight}else if(c&&c.clientHeight){d=c.clientWidth;e=c.clientHeight}else if(b.body){d=b.body.clientWidth;e=b.body.clientHeight}if(e>2*a.google_ad_height||d>2*a.google_ad_width)return g}return m}
function rd(a){var b=window,c=h,d=b.onerror;b.onerror=a;if(b.google_ad_frameborder==c)b.google_ad_frameborder=0;if(b.google_ad_output==c)b.google_ad_output="html";if($c(b.google_ad_format)){var e=b.google_ad_format.match(/^(\d+)x(\d+)_.*/);if(e){b.google_ad_width=parseInt(e[1],10);b.google_ad_height=parseInt(e[2],10);b.google_ad_output="html"}}if(b.google_ad_format==c&&b.google_ad_output=="html")b.google_ad_format=b.google_ad_width+"x"+b.google_ad_height;sd(b,document);if(b.google_num_slots_by_channel==
c)b.google_num_slots_by_channel=[];if(b.google_viewed_host_channels==c)b.google_viewed_host_channels=[];if(b.google_num_slots_by_client==c)b.google_num_slots_by_client=[];if(b.google_prev_ad_formats_by_region==c)b.google_prev_ad_formats_by_region=[];if(b.google_prev_ad_slotnames_by_region==c)b.google_prev_ad_slotnames_by_region=[];if(b.google_correlator==c)b.google_correlator=aa;if(b.google_adslot_loaded==c)b.google_adslot_loaded={};if(b.google_adContentsBySlot==c)b.google_adContentsBySlot={};if(b.google_flash_version==
c)b.google_flash_version=ia();if(b.google_new_domain_checked==c)b.google_new_domain_checked=0;if(b.google_new_domain_enabled==c)b.google_new_domain_enabled=0;b.onerror=d}function td(a){if(a in ud)return ud[a];return ud[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var ud={};function ja(){return td("msie")&&!window.opera}
function wd(a){var b={},c=a.split("?"),d=c[c.length-1].split("&"),e=0;for(;e<d.length;e++){var f=d[e].split("=");if(f[0])try{b[f[0].toLowerCase()]=f.length>1?window.decodeURIComponent?decodeURIComponent(f[1].replace(/\+/g," ")):unescape(f[1]):""}catch(j){}}return b}function xd(){var a=window,b=wd(document.URL);if(b.google_ad_override){a.google_ad_override=b.google_ad_override;a.google_adtest="on"}}function yd(a,b){for(var c in b)a["google_"+c]=b[c]}
function zd(a,b){if(!b)return a.location;return a.referrer}function Ad(a,b){if(!b&&a.google_referrer_url==h)return"0";else if(b&&a.google_referrer_url==h)return"1";else if(!b&&a.google_referrer_url!=h)return"2";else if(b&&a.google_referrer_url!=h)return"3";return"4"}function Bd(a,b,c,d){a.page_url=zd(c,d);a.page_location=h}function Cd(a,b,c,d){a.page_url=b.google_page_url;a.page_location=zd(c,d)||"EMPTY"}
function Dd(a,b){var c={},d=Yc(a,b);c.iframing=Ad(a,d);!!a.google_page_url?Cd(c,a,b,d):Bd(c,a,b,d);c.last_modified_time=b.location==c.page_url?Date.parse(b.lastModified)/1000:h;c.referrer_url=d?a.google_referrer_url:a.google_page_url&&a.google_referrer_url?a.google_referrer_url:b.referrer;return c}function Ed(a){var b={},c=a.URL.substring(a.URL.lastIndexOf("http"));b.iframing=h;b.page_url=c;b.page_location=a.location;b.last_modified_time=h;b.referrer_url=c;return b}
function sd(a,b){var c;c=a.google_page_url==h&&Fd[b.domain]?Ed(b):Dd(a,b);yd(a,c)}function id(a,b,c){if(a){var d=b.getElementById(a);if(d&&c&&c.length!=""){d.style.visibility="visible";d.innerHTML=c}}}var Fd={};Fd["ad.yieldmanager.com"]=m;var nd=/[+, ]/;window.google_render_ad=pd;var Gd={google:1,googlegroups:1,gmail:1,googlemail:1,orkut:1,googleimages:1,googleprint:1};function Hd(a){var b=a.google_page_location||a.google_page_url;if(!b)return g;b=b.toString();if(b.indexOf("http://")==0)b=b.substring(7,b.length);else if(b.indexOf("https://")==0)b=b.substring(8,b.length);var c=b.indexOf("/");if(c==-1)c=b.length;var d=b.substring(0,c),e=d.split("."),f=g;if(e.length>=3)f=e[e.length-3]in Gd;if(e.length>=2)f=f||e[e.length-2]in Gd;return f}
function Id(a,b,c){if(Hd(a)){a.google_new_domain_checked=1;return g}if(a.google_new_domain_checked==0){var d=Math.random();if(d<=c){var e="http://googleads.g.doubleclick.net/pagead/test_domain.js",f="script";b.write("<"+f+' src="'+e+'"></'+f+">");a.google_new_domain_checked=1;return m}}return g}function md(a){var b="http://googleads.g.doubleclick.net",c="http://pagead2.googlesyndication.com";if(!Hd(a)&&a.google_new_domain_enabled==1)return b;return c};function Jd(a,b){var c="script",d=Id(a,b,ga("1",0.01));d&&ja()?b.write("<"+c+' src="http://pagead2.googlesyndication.com/pagead/render_ads.js"></'+c+">"):b.write("<"+c+">window.google_render_ad();</"+c+">")}xd();rd(qd);Jd(window,document);
})()
